name: Codeflash

on:
  pull_request:
    paths:
      # So that this workflow only runs when code within the target module is modified
      - 'src/**'
  workflow_dispatch:

concurrency:
  # Any new push to the PR will cancel the previous run, so that only the latest code is optimized
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  optimize:
    name: Optimize new Python code
    # Don't run codeflash on codeflash-ai[bot] commits, prevent duplicate optimizations
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
    
    steps:
        - name: Checkout
        uses: actions/checkout@v4
        with:
        fetch-depth: 0
        - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
        python-version: "3.12"
        cache: "pip"
        - name: Install system packages
        run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsndfile1 libsndfile1-dev libjpeg-dev zlib1g-dev
        - name: Upgrade pip, setuptools and wheel
        run: |
        python -m pip install --upgrade pip setuptools wheel
        - name: Setup uv (dependency manager)
        run: |
        pip install --upgrade uv
        - name: Install Python dependencies (package + extras: test)
        run: |
      - name: ⚡️Codeflash Optimization
        run: uv run codeflash